# permissions for end users to edit gohttpservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gohttpserver-editor-role
rules:
- apiGroups:
  - apps.dlbppx.online
  resources:
  - gohttpservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dlbppx.online
  resources:
  - gohttpservers/status
  verbs:
  - get
