# permissions for end users to view gohttpservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gohttpserver-viewer-role
rules:
- apiGroups:
  - apps.dlbppx.online
  resources:
  - gohttpservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.dlbppx.online
  resources:
  - gohttpservers/status
  verbs:
  - get
