# permissions for end users to edit gohtpservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gohtpserver-editor-role
rules:
- apiGroups:
  - apps.dlbppx.online
  resources:
  - gohtpservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dlbppx.online
  resources:
  - gohtpservers/status
  verbs:
  - get
