# permissions for end users to view gohtpservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gohtpserver-viewer-role
rules:
- apiGroups:
  - apps.dlbppx.online
  resources:
  - gohtpservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.dlbppx.online
  resources:
  - gohtpservers/status
  verbs:
  - get
