---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.dlbppx.online
  resources:
  - gohtpservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dlbppx.online
  resources:
  - gohtpservers/finalizers
  verbs:
  - update
- apiGroups:
  - apps.dlbppx.online
  resources:
  - gohtpservers/status
  verbs:
  - get
  - patch
  - update
