apiVersion: apps.dlbppx.online/v1alpha1
kind: Gohtpserver
metadata:
  name: gohtpserver-sample
  namespace: demo-operator
spec:
  name: gohtpserver1
  namespace: demo-operator
  image: registry.cn-hangzhou.aliyuncs.com/my_docker_images/httpserver:v3
  replicas: 2
